project:
  type: website

website:
  title: "Myblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/anubhavmaity
      - icon: twitter
        href: https://twitter.com/MaityAnubhav
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto
